version: '3.8'
services:
  backend:
    build: ./MFA-Backend/mfa_app
    container_name: mfa-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/mfa_db
    depends_on:
      - postgres
    volumes:
      - ./MFA-Backend/mfa_app:/app

  frontend:
    build: ./MFAFRONTENDCORRECT/mfa-client
    container_name: mfa-frontend
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./MFAFRONTENDCORRECT/mfa-client:/app

  postgres:
    image: postgres:15
    container_name: mfa-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mfa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
